title: oybek
url: https://oybek.github.io
author: oybek
email: aybek.hashimov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog about gaming, programming, software development, driving,
  travelling and other my hobbies.
show_excerpts: true

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.youtube.com/@wolf_code
      icon: youtube
      color: red
    - url: https://github.com/oybek
      icon: github
      color: purple
    - url: https://t.me/wolfodav
      icon: telegram
      color: cyan
      
  avatar_source: local
  avatar_path: /public/avatar.webp

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
